### ISSUE TITLE
Not working properly on Mozilla Firefox & Microsoft Edge & Internet Explorer

### ISSUE THREAD

**Issue by zeuscronos** [vogloblinsky/angular-elements-demo#3]
Tried on Mozilla Firefox but getting the following error:

"ReferenceError: customElements is not defined"

In the other hand, I tried on Google Chrome and !!! it works properly !!!

Maybe I need to include some Javascript file like a polyfill?
I tried some of them recommended on internet with no success.

It also didn't work on Microsoft Edge and Internet Explorer.

Any idea on how to solve this?

Thanks for your help!

**Comment by vogloblinsky** [comment]
This page explains that Shadow DOM polyfill doesn't work very well in Firefox : https://developer.mozilla.org/en-US/docs/Web/Web_Components/Status_in_Firefox

I add to put encapsulation in Emulated mode of the Angular component to make it working in Firefox.
